### PR TITLE
python-base: also fix the right in the code dir

### PR DESCRIPTION
**Pull request by david-caro**
This is needed for the new travis builders to work ok, as they
actually have a different than 1000 uuid set on the code dir, and is
not writable to others.

Signed-off-by: David Caro <david@dcaro.es>

### CODE REVIEW

**Comment by david-caro** [comment]
I forgot how to compare string in c xd

**Comment by david-caro** [comment]
btw. @jacquerie this messes up you code dir on macos if you don't set the var BASE_USER_UID to you user id (iirc in mac was 500 by default).

**Comment by jacquerie** [comment]
> I forgot how to compare string in c xd

It doesn't matter for this PR, but you could have used `strncmp` (note the **n**) because you know in advance the length of the string you're looking for!

**Comment by david-caro** [comment]
> It doesn't matter for this PR, but you could have used strncmp (note the n) because you know in advance the length of the string you're looking for!
Good to know 👍

**Comment by jacquerie** [comment]
This fixing of the build requires a fixing of the build: https://travis-ci.org/inspirehep/inspire-docker/jobs/245463689#L463

**Comment by david-caro** [comment]
Dammit xd, it does not list though the available versions with the madison command... looking

**Pull request merged**
