### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by david-caro**
This runs the inspire-next tests, both unit and integration, with the newly created images before deploying to make sure the deployed images are always in a working state.

### CODE REVIEW

**Comment by kaplun** [comment]
Travis currently fail: https://travis-ci.org/inspirehep/inspire-docker/jobs/144371397#L1255

**Comment by david-caro** [comment]
That looks strange, investigating :suspect:

**Comment by mihaibivol** [comment]
Isn't this too much for this image? What happens if we want to build images when we push to master on `inspire-next`. Do we:
* Run test suite for PR
* Run test suite for merge on `master`
* On master test suite success trigger build for the `docker` repo
* Build docker `images`
* Run tests again?

IMHO the next step would be to trigger this build when we merge something on `inspire-next` so that the `pip` cache doesn't get out of date and even more we actually have some image of the frontend that we can plug into the backends of `qa.inspirehep.net`

**Comment by mihaibivol** [comment]
Maybe we can just run some smoketests instead of the full suite. It takes 7 minutes to build the image and another 20 to run the test suites one after another. I don't see much activity on this repository so that we need to check this bad that if we commit to this thing we don't break anything.

**Comment by david-caro** [comment]
You are expecting the python-base image to be build on every commit to inspire-next. I don't think that's needed, having the cache out of sync for a few days is not that relevant as the only drawback is that the build have to download the new dep (that's not so frequent either). So the idea there is to automatically rebuild the inspire-docker (that is, the python-base and elasticsearch containers) once a week with the travis cron experimental feature.
And in order to keep the inspire-next tests stable, we want to make sure they don't break before pushing the containers to dockerhub, so the tests should be after the image build and before the deploy anyhow.

About building an inspirehep docker image itself, that requires some more investigating, but that can still be done on the inspire-next repo, without having to change anything on inspire-docker in any case. And it can still be done on each merge too, just decoupled from the build of the other base images. Not sure though how useful it is to have each commit deployed to qe, maybe we can do the same cron strategy and deploy once a day, or a week instead.

**Comment by david-caro** [comment]
If the build of the images is done once a week, then the fact that it takes ~30m is not as relevant as making sure it does not break the tests (of course, all of this is my opinion)

**Comment by david-caro** [comment]
as we chatted before, I agree on running the tests with all the images at the same time, and getting rid of the parallel runs for now, but I'll open a task for that (also for the pip-accel to pip8 move).

Else this pull will become huge

**Comment by david-caro** [comment]
Opened #11 and #12

**Pull request merged**
