### PR TITLE
docker: added support for xrootd-python

### PR DESCRIPTION
**Pull request by ammirate**

### CODE REVIEW

**Comment by jacquerie** [comment]
Uhm, we're not going to need this for a while, or am I missing something in how close we are to having a working Jenkins infrastructure running on CERN's hardware, @david-caro ?

**Comment by jacquerie** [comment]
I'm not against this PR, eh, I was just surprised by it!

**Comment by david-caro** [comment]
In order to be able to install pyxrootd (on one of the other xrootd python packages) you need to have installed the python-xrootd library, that is not distributed through pypi. This work started wen the xrootd extension was being added, and was not an optional extra. I also know that there's some docker containers with eos running around cern CI that we can try to use on the jenkins at some point.

**Comment by jacquerie** [comment]
> This work started wen the xrootd extension was being added, and was not an optional extra.

Ah, I see. Shall we merge this and revert https://github.com/inspirehep/inspire-next/commit/dce0e3b3fe7df3329667e36a948313ed4984ada5 then?

**Comment by david-caro** [comment]
That would be the way to go I think, yes, there's no hurry though.

**Pull request merged**
