### PR TITLE
fix: pin setuptools version due to bad import

### PR DESCRIPTION
**Pull request by david-caro**
Should be removed once https://github.com/pypa/setuptools/pull/1044
is merged.

Signed-off-by: David Caro <david@dcaro.es>

### CODE REVIEW

**Comment by jacquerie** [comment]
It looks like `setuptools~=36` still gets installed later: https://travis-ci.org/inspirehep/inspire-docker/jobs/238278447#L2171

**Comment by david-caro** [comment]
yep, we have it redundant in the entry point...

**Comment by david-caro** [comment]
@jacquerie now it works :), merge if you are ok, I have to go, cya!

**Comment by jacquerie** [comment]
`setuptools==36.0.1` was released (https://github.com/pypa/setuptools/releases/tag/v36.0.1), so we should be able to revert this.

**Pull request merged**
