### PR TITLE
python-base: missing postgresql-devel dep

### PR DESCRIPTION
**Pull request by david-caro**
Signed-off-by: David Caro <david.caro@cern.ch>

### CODE REVIEW

**Comment by mihaibivol** [comment]
Will do a fast merge to make the build green again :)

**Comment by mihaibivol** [comment]
Can you also change the line `requirements-builder setup.py -e all` to `requirements-builder setup.py -e all -e postgresql`

**Comment by mihaibivol** [comment]
@david-caro If the build passes then we can install everything in other PRs

**Comment by david-caro** [comment]
I'll add an inspire test run as one of the steps of the build, to make sure that it does not break anything in another pr, does that sound ok?

**Comment by mihaibivol** [comment]
@david-caro I think that it's enough that we actually install everything we need (currently we were actually forgetting to cache any postgresql client library anyway). IMHO this PR should be just fine. The old Dockerfile became stable pretty fast

**Pull request merged**
